#!/bin/sh

#SBATCH --job-name="case-5"
#SBATCH --output=2_%u.%x.%j.out

#SBATCH -p compute
#SBATCH -q normal
#SBATCH -t 2-00:00:00

#SBATCH -n 196


cd $SLURM_SUBMIT_DIR
#srun ./build/src/rel_pic_1d/rel_pic_1d --wd ./data -save -record_particle_at_init --outer_Nt 5 --load false 2>&1 | tee stdout.log
srun ./build/src/rel_pic_1d/rel_pic_1d --wd ./data -save -record_particle_at_init --outer_Nt 3000 --load true 2>&1 | tee stdout.log

