#!/bin/sh

#SBATCH --job-name="case-1"
#SBATCH --output=2_%u.%x.%j.out

#SBATCH -p allnode
#SBATCH -q normal
#SBATCH -t 2-00:00:00

#SBATCH -n 360


cd $SLURM_SUBMIT_DIR
#srun ./build/src/rel_pic_1d/rel_pic_1d --wd ./data -save -record_particle_at_init --outer_Nt 5 --load false 2>&1 | tee stdout.log
srun ./build/src/rel_pic_1d/rel_pic_1d --wd ./data -save -record_particle_at_init --outer_Nt 5000 --load true 2>&1 | tee stdout.log

